
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yumak
{

using System;
    using System.Collections.Generic;
    
public partial class ArgeTasarimR
{

    public int ID { get; set; }

    public Nullable<int> ProjeID { get; set; }

    public Nullable<int> ProjeDetayID { get; set; }

    public Nullable<System.DateTime> PlanlananKatiModelCizimi { get; set; }

    public Nullable<System.DateTime> GerceklesenKatiModelCizimi { get; set; }

    public Nullable<System.DateTime> PlanlananTeknikResimCizimi { get; set; }

    public Nullable<System.DateTime> GerceklesenTeknikResimCizimi { get; set; }

    public Nullable<System.DateTime> ResimOnayTarihi { get; set; }

    public Nullable<System.DateTime> Recete { get; set; }

    public Nullable<System.DateTime> OperasyonelRecete { get; set; }

    public string AkisSemasi { get; set; }

    public Nullable<bool> TamamlanmaDurumu { get; set; }

}

}
