
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yumak
{

using System;
    using System.Collections.Generic;
    
public partial class ParcaGenelBilgiler
{

    public int ID { get; set; }

    public Nullable<int> ProjeID { get; set; }

    public Nullable<int> ProjeDetayID { get; set; }

    public string Malzeme { get; set; }

    public string HamMalzemeUretimYontemi { get; set; }

    public string Sertlik { get; set; }

    public string IsilIslem { get; set; }

    public string Kaplama { get; set; }

    public string TedarikciBilgisi { get; set; }

    public Nullable<bool> TamamlanmaDurumu { get; set; }

}

}
