
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yumak
{

using System;
    using System.Collections.Generic;
    
public partial class ProjeDetay
{

    public int ID { get; set; }

    public Nullable<int> ProjeUstID { get; set; }

    public Nullable<int> StokID { get; set; }

    public Nullable<int> KullaniciID { get; set; }

    public Nullable<double> SiraNo { get; set; }

    public string YumakNo { get; set; }

    public string Aciklama { get; set; }

    public string YeniUrunTalep { get; set; }

    public string Fizibilite { get; set; }

    public string ProsesTasarim { get; set; }

    public string IleriKalitePlanlamasiAPQP { get; set; }

    public Nullable<System.DateTime> ProjeBaslangicTarihi { get; set; }

    public Nullable<System.DateTime> PlanlananProjeTarihi { get; set; }

    public Nullable<System.DateTime> GerceklesenProjeBitisTarihi { get; set; }

    public string Durum { get; set; }

    public Nullable<bool> ParcaGenelBilgisi { get; set; }

    public Nullable<bool> ArgeTasarimBilgisi { get; set; }

    public Nullable<bool> DisHizmetBilgisi { get; set; }

    public Nullable<bool> KaliphaneBilgisi { get; set; }

    public Nullable<bool> KaliteKontrolBilgisi { get; set; }

    public Nullable<bool> UretimPlanlamaBilgisi { get; set; }

    public Nullable<bool> MontajBilgisi { get; set; }

    public Nullable<bool> SevkiyatBilgisi { get; set; }

    public Nullable<decimal> Yuzde { get; set; }

    public Nullable<int> Sayac { get; set; }

}

}
