
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yumak
{

using System;
    using System.Collections.Generic;
    
public partial class ProjeUstBilgileri
{

    public int ID { get; set; }

    public Nullable<int> StokID { get; set; }

    public Nullable<int> KullaniciID { get; set; }

    public Nullable<System.DateTime> ProjeBaslangicTarihi { get; set; }

    public Nullable<System.DateTime> PlanlananProjeTarihi { get; set; }

    public Nullable<System.DateTime> BildirimTarihi { get; set; }

    public Nullable<System.DateTime> GerceklesenProjeTarihi { get; set; }

    public string Aciklama { get; set; }

    public string Durum { get; set; }

    public string OEMNo { get; set; }

    public Nullable<decimal> Yuzde { get; set; }

}

}
