
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yumak
{

using System;
    using System.Collections.Generic;
    
public partial class Stok
{

    public int ID { get; set; }

    public string YumakNo { get; set; }

    public string UrunAd { get; set; }

    public byte[] Resim { get; set; }

    public string OEMNo { get; set; }

    public Nullable<int> ProjeID { get; set; }

    public Nullable<int> ProjeDetayID { get; set; }

}

}
