
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yumak
{

using System;
    using System.Collections.Generic;
    
public partial class Toplanti
{

    public int ID { get; set; }

    public Nullable<int> ProjeID { get; set; }

    public Nullable<int> ProjeDetayID { get; set; }

    public Nullable<int> EtapNo { get; set; }

    public string ToplantiAd { get; set; }

    public string ToplantiDetay { get; set; }

}

}
