

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace yumak
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class YumakEntities : DbContext
{
    public YumakEntities()
        : base("name=YumakEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<ArgeTasarimR> ArgeTasarimRs { get; set; }

    public DbSet<DisHizmet> DisHizmets { get; set; }

    public DbSet<KaliphaneAparat> KaliphaneAparats { get; set; }

    public DbSet<KaliteKontrol> KaliteKontrols { get; set; }

    public DbSet<Kullanici> Kullanicis { get; set; }

    public DbSet<Montaj> Montajs { get; set; }

    public DbSet<ParcaGenelBilgiler> ParcaGenelBilgilers { get; set; }

    public DbSet<SevkiyatPaketleme> SevkiyatPaketlemes { get; set; }

    public DbSet<Stok> Stoks { get; set; }

    public DbSet<Toplanti> Toplantis { get; set; }

    public DbSet<UretimPlanlama> UretimPlanlamas { get; set; }

    public DbSet<vKullaniciProjeUst> vKullaniciProjeUsts { get; set; }

    public DbSet<ProjeDetay> ProjeDetays { get; set; }

    public DbSet<ProjeUstBilgileri> ProjeUstBilgileris { get; set; }

}

}

